### ISSUE TITLE
Look at remaining non working datasets

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaDatasets.jl#5]
The tests currently exclude a number of data files because they throw errors. We should go through that list and figure out whether we can enable them.

**Comment by mcmcgrath13** [comment]
@davidanthoff I took a closer look at the geo-related files and with a few minor code changes I could parse the "earthquakes" file into a format that was strictly speaking iterable, and I was successfully able to pass it into a vega spec and plot it, but I don't think it would be useful for anything else (most of the fields are dictionaries).  

The topojson files could be handled similarly, but the issue is there are multiple ways they could be parsed into geojson depending on the type of geography you want to look at (e.g. "states" vs "counties") - so that would either need another field passed or a geography chosen for each file, neither of which I'm super keen on.

I'm not sure this is worth pursuing any of these options as the tables wouldn't likely be useful for anything besides piping them into vega/vega-lite specs and at that point you've parsed a json file into a table to parse it back into json for vega, which is a bit circular.  Thoughts?

**Comment by davidanthoff** [comment]
Yeah, I think I agree that we wouldn't want to read those in.

We could just return a `Path` instance from `dataset` if it is one of those datasets that we don't want to read in, and I think VegaLite.jl should already handle those properly?

**Comment by mcmcgrath13** [comment]
Makes sense, then they won't be marked as `isiterable` which is probably for the best as that's where the not-helpful error message was coming from (trying to iterate nothing).  I played around a bit more with the `Path` functionality in VegaLite and ran into issues with browser-based viewing as vega didn't have access to the file system - what do you think about changing that to read in the file as a string to the `values` property instead of the path to the `url` property?

**Comment by davidanthoff** [comment]
Ha, you discovered my main pain point right now :) I was actually going to open an issue how we can more generally fix this file loading issue (it is broken right now in the browser preview, ElectronDisplay.jl and VS Code, it only works properly with the `save` functions). And I was kind of hoping you might be able to help with that because my JavaScript chops are pretty much non existent. I'll try to write up what the problem is and what I'm thinking might work as a solution in an issue over in VegaLite.jl.

**Comment by davidanthoff** [comment]
I think we can close this, right?
